- server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
> test :  be-test-test#1

- server/mainProject/build.gradle
- server/mainProject/src/main/java/com/codestates/mainProject/auth/WebConfig.java
- server/mainProject/src/main/java/com/codestates/mainProject/auth/config/PasswordEncoderConfig.java
- server/mainProject/src/main/java/com/codestates/mainProject/auth/config/SecurityConfiguration.java
- server/mainProject/src/main/java/com/codestates/mainProject/auth/dto/LoginDto.java
- server/mainProject/src/main/java/com/codestates/mainProject/auth/dto/TokenPrincipalDto.java
- server/mainProject/src/main/java/com/codestates/mainProject/auth/filter/JwtAuthenticationFilter.java
- server/mainProject/src/main/java/com/codestates/mainProject/auth/filter/JwtVerificationFilter.java
- server/mainProject/src/main/java/com/codestates/mainProject/auth/handler/MemberAccessDeniedHandler.java
- server/mainProject/src/main/java/com/codestates/mainProject/auth/handler/MemberAuthenticationEntryPoint.java
- server/mainProject/src/main/java/com/codestates/mainProject/auth/handler/MemberAuthenticationFailureHandler.java
- server/mainProject/src/main/java/com/codestates/mainProject/auth/handler/MemberAuthenticationSuccessHandler.java
- server/mainProject/src/main/java/com/codestates/mainProject/auth/handler/OAuth2MemberSuccessHandler.java
- server/mainProject/src/main/java/com/codestates/mainProject/auth/jwt/JwtTokenizer.java
- server/mainProject/src/main/java/com/codestates/mainProject/auth/userdetails/MemberDetailsService.java
- server/mainProject/src/main/java/com/codestates/mainProject/auth/utils/CustomAuthorityUtils.java
- server/mainProject/src/main/java/com/codestates/mainProject/auth/utils/ErrorResponder.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/controller/HelloHomeController.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/dto/MemberDto.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/mapper/MemberMapper.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/repository/MemberRepository.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/service/OAuth2MemberService.java
- server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
- server/mainProject/src/main/resources/application-local.yaml
- server/mainProject/src/main/resources/templates/hello-oauth2.html
- server/mainProject/src/main/resources/templates/index.html
> Feat : be-feat-JwtToken인증구현#39

- server/mainProject/src/main/java/com/codestates/mainProject/auth/config/SecurityConfiguration.java
- server/mainProject/src/main/java/com/codestates/mainProject/auth/filter/JwtAuthenticationFilter.java
- server/mainProject/src/main/java/com/codestates/mainProject/auth/jwt/JwtTokenizer.java
- server/mainProject/src/main/java/com/codestates/mainProject/exception/ExceptionCode.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/dto/MemberDto.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/mapper/MemberMapper.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
- server/mainProject/src/main/resources/templates/index.html
> Feat : 컨트롤러,서비스구현#42#43

- server/mainProject/src/main/java/com/codestates/mainProject/auth/WebConfig.java
- server/mainProject/src/main/java/com/codestates/mainProject/auth/config/SecurityConfiguration.java
- server/mainProject/src/main/java/com/codestates/mainProject/exception/ExceptionCode.java
- server/mainProject/src/main/java/com/codestates/mainProject/image/FileStorageProperties.java
- server/mainProject/src/main/java/com/codestates/mainProject/image/FileStorageService.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/dto/MemberDto.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
- server/mainProject/src/main/java/com/codestates/mainProject/playList/mapper/PlayListMapper.java
- server/mainProject/src/main/resources/application-local.yaml
> Feat : Image파일등록,조회기능구현#57

- client/src/components/sign/Signin.tsx
- client/src/components/sign/Signup.tsx
- client/src/types/LoginInput.ts
feat : SignUp 페이지 기능구현 / userinfo 인터페이스 추가 
comment : SignUp 페이지 내 함수들 jsdoc로 설명추가.
> feat : SignUp 페이지 기능구현 / userinfo 인터페이스 추가 / comment : SignUp 페이지 내 함수들 jsdoc로 설명추가.

- client/src/components/NotFound.tsx
- client/src/components/mixing/Mixing.tsx
- client/src/components/sign/Signin.tsx
- client/src/components/sign/Signup.tsx
- client/src/pages/Routingpages.tsx
style : 인풋창 포커스 시 바텀보더 크기 및 색상 변경으로 포커스 상태를 보여줌
refactor : 믹싱페이지 경로 추가 및 404페이지 홈버튼 클릭 시 홈화면으로 라우팅
design : 믹싱페이지 레이아웃
design : 인풋창 포커스 상태 시 보더바텀의 색과 크기변하면서 포커스상태 시각적 표현
> 로그인/회원가입창 인풋 포커스효과 적용 / 믹싱페이지 라우팅설정

- server/mainProject/src/main/java/com/codestates/mainProject/music/entity/Music.java
> Fix : dev-fix-뮤직엔티티변수명통일#69

- server/mainProject/src/main/java/com/codestates/mainProject/exception/ExceptionCode.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/service/MusicService.java
> Feat : dev-feat-음원삭제기능구현#46

- server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicLike/entity/MusicLike.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicLike/repository/MusicLikeRepository.java
> Feat : dev-feat-MusicLike구현#85

- server/mainProject/build.gradle
- server/mainProject/src/main/java/com/codestates/mainProject/audit/Auditable.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/controller/HelloHomeController.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
- server/mainProject/src/main/java/com/codestates/mainProject/playList/controller/PlayListController.java
- server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
- server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
- server/mainProject/src/main/java/com/codestates/mainProject/playList/mapper/PlayListMapper.java
- server/mainProject/src/main/java/com/codestates/mainProject/playListLike/service/PlayListLikeService.java
- server/mainProject/src/main/java/com/codestates/mainProject/security/auth/dto/TokenPrincipalDto.java
- server/mainProject/src/main/java/com/codestates/mainProject/security/auth/filter/JwtAuthenticationFilter.java
- server/mainProject/src/main/java/com/codestates/mainProject/security/auth/filter/JwtVerificationFilter.java
- server/mainProject/src/main/java/com/codestates/mainProject/security/auth/handler/OAuth2MemberSuccessHandler.java
- server/mainProject/src/main/java/com/codestates/mainProject/security/config/SecurityConfiguration.java
- server/mainProject/src/main/java/com/codestates/mainProject/security/config/WebConfig.java
> Fix : PlayList오류 수정 및 권한추가#89

- server/mainProject/src/main/java/com/codestates/mainProject/MainProjectApplication.java
- server/mainProject/src/main/java/com/codestates/mainProject/audit/Auditable.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/dto/MemberDto.java
- server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
> Fix : Auditable수정#91

- client/package-lock.json
- client/package.json
> 라이브러리 conflict 수정

- server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/dto/AuthLoginDto.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/mapper/MemberMapper.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
- server/mainProject/src/main/java/com/codestates/mainProject/security/auth/attributes/OAuthAttributes.java
- server/mainProject/src/main/java/com/codestates/mainProject/security/auth/filter/JwtAuthenticationFilter.java
- server/mainProject/src/main/java/com/codestates/mainProject/security/auth/handler/OAuth2MemberSuccessHandler.java
- server/mainProject/src/main/resources/application-local.yaml
> Feat : 네이버 oauth2 로그인 기능 구현#105

- server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/repository/MemberRepository.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
> Feat : 네이버 oauth2 로그인 및 회원가입 기능 구현#107

- server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/service/MusicService.java
> Fix : dev-fix-Music카테고리수정#109

- server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
- server/mainProject/src/main/java/com/codestates/mainProject/security/auth/handler/OAuth2MemberSuccessHandler.java
- server/mainProject/src/main/resources/application-server.yml
> Refactor : Member 코드 리팩터링#138

- server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/entity/Music.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/repository/MusicRepository.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/service/MusicService.java
> Fix : dev-fix-Music카테고리 일부수정#155

- client/src/components/sign/Loading.tsx
- client/src/components/sign/Signin.tsx
> refactor : 로컬경로 => S3 경로로 변경

- client/src/components/sign/Loading.tsx
> fix : 카카오 리다이렉트 주소 수정

- client/src/App.tsx
- client/src/components/Nav/Navigete.tsx
- client/src/components/sign/Loading.tsx
[fix : 카카오 oauth로그인 시, 이메일 제공 동의 안하는 엣지케이스 커버](https://github.com/codestates-seb/seb43_main_017/commit/08f56f93ba1f4a3a65f433d38858fed1cc69fa33)
[refactor : 마이페이지 아이콘 => 로그인시 프로필사진 대체/비로그인시 로그인모달창](https://github.com/codestates-seb/seb43_main_017/commit/a9dd2c173db12bd2e366c5ca91b3ea50410414fa)
> fix : 카카오 oauth로그인 시, 이메일 제공 동의 안하는 엣지케이스 커버

- server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/dto/MusicDto.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/repository/MusicRepository.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/service/MusicService.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicComment/controller/MusicCommentController.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicComment/dto/MusicCommentDto.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicComment/mapper/MusicCommentMapper.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicComment/service/MusicCommentService.java
> playListMusic조회기능수정 및 MusicComment기능수정

- server/mainProject/src/main/java/com/codestates/mainProject/exception/ExceptionCode.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicComment/controller/MusicCommentController.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicComment/service/MusicCommentService.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicLike/controller/MusicLikeController.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicLike/dto/MusicLikeDto.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicLike/mapper/MusicLikeMapper.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicLike/service/MusicLikeService.java
> Fix:dev-fix-MusicLike기능수정#177

- server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/service/MusicService.java
- server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
> Fix:dev-fix-MusicController수정#180

- client/.env
- client/src/components/sign/GoogleBtn.tsx
- client/src/components/sign/KakaoBtn.tsx
- client/src/components/sign/Loading.tsx
- client/src/components/sign/NaverBtn.tsx
- client/src/components/sign/Signin.tsx
- client/src/components/sign/Signup.tsx
[refactor : 시크릿키/클라이언트아이디/API URL등 env파일로 관리](https://github.com/codestates-seb/seb43_main_017/commit/c9103b296dc132c98898417b5511dc99b4fd4a0e)
> refactor : 시크릿키/클라이언트아이디/API URL등 env파일로 관리

- server/mainProject/src/main/java/com/codestates/mainProject/exception/ExceptionCode.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/dto/MusicDto.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/repository/MusicRepository.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/service/MusicService.java
- server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
> Fix:dev-fix-patchMusic메서드수정#190

- server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/repository/MusicRepository.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/service/MusicService.java
> Feat:dev-feat-키워드검색구현#192

- server/mainProject/.idea/.gitignore
- server/mainProject/.idea/aws.xml
- server/mainProject/.idea/gradle.xml
- server/mainProject/.idea/jarRepositories.xml
- server/mainProject/src/main/java/com/codestates/mainProject/security/config/SecurityConfiguration.java
> Feat : FilterChain 권한관련 추가#199

- server/mainProject/src/main/java/com/codestates/mainProject/exception/ExceptionCode.java
- server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
- server/mainProject/src/main/java/com/codestates/mainProject/playListComment/service/CommentService.java
- server/mainProject/src/main/java/com/codestates/mainProject/playListLike/service/PlayListLikeService.java
- server/mainProject/src/main/java/com/codestates/mainProject/tags/controller/TagController.java
- server/mainProject/src/main/java/com/codestates/mainProject/tags/dto/TagDto.java
- server/mainProject/src/main/java/com/codestates/mainProject/tags/entity/Tag.java
- server/mainProject/src/main/java/com/codestates/mainProject/tags/repository/TagRepository.java
- server/mainProject/src/main/java/com/codestates/mainProject/tags/service/TagService.java
태그 구현
playlist, like, comment 작성자, 관리자 구분 로직 수정
> be-feat-tags#183 태그 구현

- client/src/components/mixing/Mixing.tsx
- client/src/components/mixing/VideoPlayer.tsx
- client/src/components/mixing/VideoUpdate.tsx
- client/src/components/sign/KakaoBtn.tsx
- client/src/components/sign/Loading.tsx
[fix : api url 수정](https://github.com/codestates-seb/seb43_main_017/commit/dccc90dc82e1ac76c3b3d54e2ed373492dcd5552)
[feat : 믹싱페이지 드랍존 세팅](https://github.com/codestates-seb/seb43_main_017/commit/651cd9a052f787cdd022da59b7e94e4c258377f1)
[feat : 믹싱페이지 비디오 업로드 테스트](https://github.com/codestates-seb/seb43_main_017/commit/9e8cb591838db675add6273888d9759377b67417)
> feat : 믹싱페이지 드랍존 세팅

- server/mainProject/src/main/java/com/codestates/mainProject/exception/ExceptionCode.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
- server/mainProject/src/main/java/com/codestates/mainProject/memberMusic/service/MemberMusicService.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/entity/Music.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicLike/service/MusicLikeService.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicTag/controller/MusicTagController.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicTag/dto/MusicTagDto.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicTag/entity/MusicTag.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicTag/repository/MusicTagRepository.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicTag/service/MusicTagService.java
- server/mainProject/src/main/java/com/codestates/mainProject/security/config/SecurityConfiguration.java
> Feat : MusicTag 구현 #208

- client/src/components/sign/Loading.tsx
- client/src/recoil/Atoms.tsx
[feat : 멤버아이디 로컬스토리지로 저장](https://github.com/codestates-seb/seb43_main_017/commit/bbc5b9d4064dd6fa6960cf6e423802d7f97b98a0)
[fix : 아톰 공백 문법에러 수정](https://github.com/codestates-seb/seb43_main_017/commit/eab95c47a224d074c3034e9335aa28f7c3c37eee)
> feat : 멤버아이디 로컬스토리지로 저장

- client/src/components/Nav/Navigete.tsx
fix : 로컬로그인 시 로그인 요청이 계속 되는 것 수정
> fix : 로컬로그인 시 로그인 요청이 계속 되는 것 수정

- client/src/App.tsx
- client/src/components/sign/Signin.tsx
fix : 로컬로그인 시 로그인 요청이 계속 되는 것 수정
> refactor : 로컬스토리지 안쓰는 정보 제거

- client/src/App.tsx
refactor : 로그인이 필수인 페이지에서 로그아웃 시, 메인화면으로 리다이렉트
> refactor : 로그인이 필수인 페이지에서 로그아웃 시, 메인화면으로 리다이렉트

- client/src/components/sign/Loading.tsx
> refactor : 로컬스토리지에 유저정보 저장

- client/src/App.tsx
> fix : 로그아웃시 로컬스토리지 이메일 삭제

- client/src/App.tsx
- client/src/components/mixing/Mixing.tsx
> fix : 로컬스토리지 유저닉네임 지워지도록 수정

- server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
- server/mainProject/src/main/java/com/codestates/mainProject/tags/controller/TagController.java
- server/mainProject/src/main/java/com/codestates/mainProject/tags/dto/TagDto.java
- server/mainProject/src/main/java/com/codestates/mainProject/tags/entity/Tag.java
- server/mainProject/src/main/java/com/codestates/mainProject/tags/repository/TagRepository.java
- server/mainProject/src/main/java/com/codestates/mainProject/tags/service/TagService.java
> Feat : 태그에 카테고리 추가 및 태그리팩터링 #237

- client/src/components/sign/Loading.tsx
- client/src/components/sign/Signin.tsx
fix : 로그인 시 멤버아이디 받아오지 못하는 에러 수정
> fix : 로그인 시 멤버아이디 받아오지 못하는 에러 수정

- client/src/components/sign/Signin.tsx
refactor : 로컬 로그인시 이메일 이름 로컬스토리지 추가
> refactor : 로컬 로그인시 이메일 이름 로컬스토리지 추가

- server/mainProject/src/main/java/com/codestates/mainProject/musicComment/dto/MusicCommentDto.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicComment/mapper/MusicCommentMapper.java
- server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
- server/mainProject/src/main/java/com/codestates/mainProject/playList/repository/PlayListRepository.java
- server/mainProject/src/main/java/com/codestates/mainProject/search/controller/SearchController.java
- server/mainProject/src/main/java/com/codestates/mainProject/search/service/SearchService.java
> Feat:dev-feat-playList검색구현#254

- server/mainProject/src/main/java/com/codestates/mainProject/playListLike/entity/PlayListLike.java
- server/mainProject/src/main/java/com/codestates/mainProject/security/config/SecurityConfiguration.java
- server/mainProject/src/main/resources/application-local.yaml
> Feat : playlistTtag관련 보안설정#270

- server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/dto/MusicDto.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/entity/Music.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/service/MusicService.java
- server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
- server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
- server/mainProject/src/main/java/com/codestates/mainProject/tags/entity/Tag.java
- server/mainProject/src/main/resources/application-server.yml
> Feat : Music응답에 태그이름 추가 및 기타수정#276

- client/src/components/mixing/LikedList.tsx
- client/src/components/mixing/Mixing.tsx
- client/src/components/mixing/VideoPlayer.tsx
- client/src/components/mixing/VideoUpdate.tsx
> feat : 믹싱페이지 구현완료

- server/mainProject/.idea/aws.xml
- server/mainProject/src/main/java/com/codestates/mainProject/playListLike/controller/PlayListLikeController.java
- server/mainProject/src/main/java/com/codestates/mainProject/playListLike/service/PlayListLikeService.java
> Fix : PlaylistLike 기타 수정 #285

- client/src/components/mixing/LikedList.tsx
[fix : audio src 경로 수정](https://github.com/codestates-seb/seb43_main_017/commit/6b57fe111650da30fe687ecd4646bf96c4bebc4c)
[fix : 현재 곡 알려주는 로직 구현](https://github.com/codestates-seb/seb43_main_017/commit/6d4fcd07dbb362f05667ad18628c01fb6431ba20)
> fix : audio src 경로 수정

- server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/service/MusicService.java
- server/mainProject/src/main/java/com/codestates/mainProject/search/controller/SearchController.java
> Fix:Search 카테고리에 페이지네이션 수정

- server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicLike/service/MusicLikeService.java
> Fix : 음악추천기능 중복노래 안 들어가게 수정 #293

- server/mainProject/.idea/aws.xml
- server/mainProject/src/main/java/com/codestates/mainProject/music/mapper/MusicMapper.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/repository/MusicRepository.java
- server/mainProject/src/main/java/com/codestates/mainProject/musicLike/mapper/MusicLikeMapper.java
> Refactor:Music 카테고리 리팩토링#306

- client/src/components/mixing/LikedList.tsx
- client/src/components/mixing/Mixing.tsx
- client/src/components/mixing/VideoPlayer.tsx
- client/src/components/mixing/VideoUpdate.tsx
[refactor : 믹싱페이지 동영상 업로드 해야만 LIKE MUSIC 창 나오도록 수정](https://github.com/codestates-seb/seb43_main_017/commit/8fe1ee9[refactor : 믹싱페이지 JSDOC 작성 및 좋아요 음악 없을 시 대체 텍스트 설정](https://github.com/codestates-seb/seb43_main_017/commit/c7458a5dbeb706b0ac5cda84a834d9760100be80)18722d612a3cab99604a549840fdab342)
> refactor : 믹싱페이지 동영상 업로드 해야만 LIKE MUSIC 창 나오도록 수정

- server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
- server/mainProject/src/main/java/com/codestates/mainProject/music/service/MusicService.java
> Fix:musicController기능수정#312

- client/src/components/mixing/LikedList.tsx
- client/src/components/mixing/Mixing.tsx
- client/src/components/mixing/VideoPlayer.tsx
- client/src/components/mixing/VideoUpdate.tsx
- client/src/components/mypage/ModifyPlaylist.tsx
> design : 믹싱페이지 반응형 구현

- client/src/App.tsx
- client/src/components/mixing/Mixing.tsx
> design :  z-index 순서 변경

- server/mainProject/.idea/aws.xml
- server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
- server/mainProject/src/main/java/com/codestates/mainProject/security/auth/handler/OAuth2MemberSuccessHandler.java
> Feat : 로컬 및 각 oAuth2 이메일 구분기능구현 #324

- client/src/components/musiclist/Musiclist.tsx
- client/src/components/musiclist/SideIcon.tsx
- client/src/recoil/Atoms.tsx
> fix : 머지 후 컨플릭 수정

- client/src/components/musiclist/AddListMusic.tsx
- client/src/components/musiclist/Musiclist.tsx
[feat : 플레이리스트에 음악추가 구현](https://github.com/codestates-seb/seb43_main_017/commit/8ac2dd802ffc2356b12ac71b88f1675eda37ae1e)
> feat : 플레이리스트에 음악추가 구현

- client/src/components/musiclist/AddListMusic.tsx
- client/src/components/musiclist/Musiclist.tsx
- client/src/components/mypage/Myplaylist.tsx
> design : 플레이리스트 추가 모달창 반응형 구현

- client/src/components/musiclist/AddListMusic.tsx
design : 웹 브라우저 사이즈 마이 플레이리스트 width 조정
> design : 웹 브라우저 사이즈 마이 플레이리스트 width 조정

- client/src/components/mixing/LikedList.tsx
[fix : 안쓰는 리코일스테이트 변경](https://github.com/codestates-seb/seb43_main_017/commit/1d546c373701b29985e31f1bb2bc946973de1574)
> fix : 안쓰는 리코일스테이트 변경

- client/src/components/mixing/VideoPlayer.tsx
- client/src/components/mixing/VideoUpdate.tsx
refactor : 불필요한 임포트 삭제 및 jsdocs 추가
> refactor : 불필요한 임포트 삭제 및 jsdocs 추가

- client/public/index.html
- client/src/components/mixing/Mixing.tsx
- client/src/components/mypage/Mypage.tsx
- client/src/components/sign/Loading.tsx
[refactor : 로그아웃시 모든 토큰 및 정보 제거](https://github.com/codestates-seb/seb43_main_017/commit/06d55a924b5c6411542e33d15a795397a0e7b9c6)
[refactor : 로그아웃시 모든 토큰 및 정보 제거](https://github.com/codestates-seb/seb43_main_017/commit/06d55a924b5c6411542e33d15a795397a0e7b9c6)
[fix : 구글 이메일 뒤에 식별번호 제거](https://github.com/codestates-seb/seb43_main_017/commit/05b3da9d109a9166e8318f158f2f0be90a58064f)
> refactor : 로그아웃시 모든 토큰 및 정보 제거

- client/src/components/mixing/LikedList.tsx
- client/src/components/mixing/Mixing.tsx
- client/src/components/sign/Loading.tsx
- client/src/recoil/Atoms.tsx
[fix : 카카오 로그인 시 , 이메일 제공동의 안한 유저 메인화면으로 리다이렉트,토큰삭제](https://github.com/codestates-seb/seb43_main_017/commit/ad9b7146928b481371a5ac143f4455d19678e044)
[design : 믹싱페이지 영상 교체버튼 좀 더 직관적인 아이콘으로 변경](https://github.com/codestates-seb/seb43_main_017/commit/5006f51c29e960e36a9f64dd9ea926e1cc37fad9)
> fix : 카카오 로그인 시 , 이메일 제공동의 안한 유저 메인화면으로 리다이렉트,토큰삭제

- client/src/components/mixing/Mixing.tsx
[refactor : 음원 선택 안할 시 컨트롤바 비활성화](https://github.com/codestates-seb/seb43_main_017/commit/5dd2245af6691411ea2f99d1c44005ef67320c94)
> refactor : 음원 선택 안할 시 컨트롤바 비활성화

- server/mainProject/src/main/java/com/codestates/mainProject/exception/ExceptionCode.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
- server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
- server/mainProject/src/main/java/com/codestates/mainProject/security/auth/controller/TokenController.java
- server/mainProject/src/main/java/com/codestates/mainProject/security/auth/filter/JwtVerificationFilter.java
- server/mainProject/src/main/java/com/codestates/mainProject/security/auth/handler/OAuth2MemberSuccessHandler.java
- server/mainProject/src/main/java/com/codestates/mainProject/security/auth/jwt/JwtTokenizer.java
- server/mainProject/src/main/java/com/codestates/mainProject/security/auth/service/TokenService.java
- server/mainProject/src/main/resources/application-local.yaml
- server/mainProject/src/main/resources/application-server.yml
> Feat : Refresh 토큰 관련 코드 추가#367

- client/public/index.html
fix: https 사이트에서 http 사이트 요청 시 Mixed content 에러
> fix: https 사이트에서 http 사이트 요청 시 Mixed content 에러

- client/src/components/main/Info.tsx
- client/src/components/sign/GoogleBtn.tsx
http://ec2-54-180-178-227.ap-northeast-2.compute.amazonaws.com:8080/oauth2/authorization/google => http://ec2-54-180-178-227.ap-northeast-2.compute.amazonaws.com:8080/oauth2/authorization/google
> fix : 구글 로그인 url 변경

- client/src/App.tsx
- client/src/components/Nav/Navigete.tsx
- client/src/components/main/Info.tsx
- client/src/components/mixing/GuideModal.tsx
- client/src/components/mixing/LikedList.tsx
- client/src/components/mixing/Mixing.tsx
- client/src/recoil/Atoms.tsx
[fix : 인포 페이지에서 피팅룸으로 이동 시, 토큰없이도 이동되는 엣지케이스 수정](https://github.com/codestates-seb/seb43_main_017/commit/8870a024d856efebc5f315a4a29be510ce159f99)
[refactor : 피팅룸 음원url https로 변경](https://github.com/codestates-seb/seb43_main_017/commit/58c07095eae510ed5a9f68099ac78098cf4d307c)
[feat : 피팅룸 가이드 모달창 생성](https://github.com/codestates-seb/seb43_main_017/commit/8250e339afb90d8b61bba58f5a15bdf9630d1fb4)
> feat : 피팅룸 페이지 가이드 영상 밑 안내문구 추가
